import { useState } from "react";
import { Activity, AlertTriangle, Archive, CheckCircle2, Download, ExternalLink, Eye, FileSearch, Globe2, Info, LockKeyhole, Network, Play, RefreshCw, ScanSearch, ShieldCheck, SlidersHorizontal, Trash2, Wifi } from "lucide-react";
import type { DeviceProfile, DiagnosticResult, ScanProgress, ThreatFinding, ToolStatus } from "../types";

export function SectionHeader({ title, description }: { title: string; description: string }) { return <div className="section-heading"><h2>{title}</h2><p>{description}</p></div>; }

export function ScansView({ tools, progress, onStart, onClamScan, onCancel }: { tools: ToolStatus[]; progress?: ScanProgress; onStart: (type: "smart" | "quick" | "full" | "network", engine: "local" | "defender" | "clamav") => void; onClamScan: () => void; onCancel: () => void }) {
  const clam = tools.find(t => t.id === "clamav");
  return <div className="view-content"><SectionHeader title="Scanning tools" description="Run explicit, non-destructive checks using local protection engines."/>
    {progress && <section className="scan-progress" aria-live="polite"><div><span className="spinner"/><strong>{progress.message}</strong><small>{progress.state} · {progress.percent}%</small></div><div className="progress-track"><i style={{width: `${progress.percent}%`}}/></div>{progress.state === "running" && <button onClick={onCancel}>Cancel scan</button>}</section>}
    <div className="feature-grid scan-grid"><article className="feature-card featured"><span className="feature-icon"><ScanSearch/></span><h3>Smart scan</h3><p>Checks Windows protection, updates, firewall, VPN, installed tools, recent findings, and network members.</p><ul><li>Fast local status checks</li><li>No files changed</li><li>Recommended starting point</li></ul><button className="primary-button" onClick={() => onStart("smart", "local")}><Play size={17}/>Start smart scan</button></article>
    <article className="feature-card"><span className="feature-icon"><ShieldCheck/></span><h3>Defender quick scan</h3><p>Uses Windows Security to check common threat locations. Starts only after your confirmation.</p><button onClick={() => onStart("quick", "defender")}><Play size={17}/>Run quick scan</button></article>
    <article className="feature-card"><span className="feature-icon"><FileSearch/></span><h3>Full PC scan</h3><p>Can take several hours and use significant system resources. No automatic remediation.</p><button onClick={() => onStart("full", "defender")}><Play size={17}/>Review full scan</button></article>
    <article className="feature-card"><span className="feature-icon"><Activity/></span><h3>ClamAV on-demand</h3><p>Secondary file scanning only. It does not provide real-time protection on Windows.</p><button disabled={!clam?.installed} onClick={onClamScan}>{clam?.installed ? "Choose a file" : "ClamAV not detected"}</button></article>
    <article className="feature-card"><span className="feature-icon"><Network/></span><h3>Private LAN discovery</h3><p>Inventories your detected private network. Port checks require separate explicit consent.</p><button onClick={() => onStart("network", "local")}><Play size={17}/>Discover devices</button></article>
    <article className="feature-card"><span className="feature-icon"><Globe2/></span><h3>Advanced analysis</h3><p>Open Wireshark or Nmap if installed. Sentinel Local never captures packets silently.</p><button>Detect advanced tools</button></article></div></div>;
}

export function ThreatsView({ findings, onRefresh, onAction }: { findings: ThreatFinding[]; onRefresh: () => void; onAction: (finding: ThreatFinding, action: "inspect" | "quarantine" | "remove") => Promise<void> }) {
  const [selected, setSelected] = useState<ThreatFinding>();
  const [pending, setPending] = useState<"quarantine" | "remove">();
  return <div className="view-content"><SectionHeader title="Threat management" description="Review evidence before taking action. Nothing is removed automatically."/>
    {findings.length === 0 && <div className="notice success"><CheckCircle2/><span><strong>No active findings</strong><small>Windows Security and completed Sentinel Local scans did not return current findings.</small></span><button onClick={onRefresh}>Refresh</button></div>}
    <section className="table-panel"><div className="panel-title"><h3>Live findings</h3><span className={`badge ${findings.length ? "review-badge" : "good-badge"}`}>{findings.length} active</span></div><table><thead><tr><th>Finding</th><th>Engine</th><th>Confidence</th><th>Detected</th><th>Actions</th></tr></thead><tbody>{findings.length === 0 ? <tr className="empty-row"><td colSpan={5}><ShieldCheck/><strong>No findings to review</strong><span>New Defender or ClamAV detections will appear here.</span></td></tr> : findings.map(f => <tr key={f.id}><td><strong>{f.classification}</strong><small>{f.location}</small></td><td>{f.engine}</td><td>{f.confidence}</td><td>{new Date(f.detectedAt).toLocaleString()}</td><td><div className="threat-actions"><button onClick={() => setSelected(f)}><Eye size={15}/>Inspect</button><button onClick={() => { setSelected(f); setPending("quarantine"); }}><Archive size={15}/>Quarantine</button><button className="danger-button" onClick={() => { setSelected(f); setPending("remove"); }}><Trash2 size={15}/>Remove</button></div></td></tr>)}</tbody></table></section>
    <section className="simulation-panel"><Info/><div><strong>Protected remediation boundary</strong><p>ClamAV findings can be moved into Sentinel Local's private quarantine. Microsoft Defender findings open Windows Security for remediation. Permanent removal requires a separate confirmation and only deletes a Sentinel-quarantined copy.</p></div></section>
    {selected && !pending ? <div className="dialog-backdrop" role="presentation"><div className="dialog threat-dialog" role="dialog" aria-modal="true" aria-labelledby="finding-title"><h3 id="finding-title">{selected.classification}</h3><dl className="detail-list"><div><dt>Engine</dt><dd>{selected.engine}</dd></div><div><dt>Severity</dt><dd>{selected.severity}</dd></div><div><dt>Confidence</dt><dd>{selected.confidence}</dd></div><div><dt>Location</dt><dd>{selected.location}</dd></div><div><dt>SHA-256</dt><dd className="break-value">{selected.sha256}</dd></div><div><dt>Detected</dt><dd>{new Date(selected.detectedAt).toLocaleString()}</dd></div></dl><div className="dialog-actions"><button onClick={() => setSelected(undefined)}>Close</button><button className="primary-button" onClick={() => void onAction(selected, "inspect")}>Inspect with source protection</button></div></div></div> : null}
    {selected && pending ? <div className="dialog-backdrop" role="presentation"><div className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h3 id="confirm-title">Confirm {pending}</h3><p>{pending === "quarantine" ? "The file will be moved into Sentinel Local's private quarantine if it is a verified ClamAV finding. Defender findings will open Windows Security." : "Permanent removal is only available after Sentinel Local has quarantined the file. This cannot be undone."}</p><label className="confirm-row"><input type="checkbox" id="threat-confirm"/>I understand the impact</label><div className="dialog-actions"><button onClick={() => setPending(undefined)}>Cancel</button><button className={pending === "remove" ? "danger-button" : "primary-button"} onClick={async () => { const box = document.getElementById("threat-confirm") as HTMLInputElement; if (!box.checked) { box.focus(); return; } await onAction(selected, pending); setPending(undefined); setSelected(undefined); }}>{pending === "remove" ? "Permanently remove" : "Move to quarantine"}</button></div></div></div> : null}
  </div>;
}

export function PrivacyView({ tools, onOpen }: { tools: ToolStatus[]; onOpen: (id: string) => void }) {
  return <div className="view-content"><SectionHeader title="Privacy controls" description="Understand each protection layer without overstating anonymity."/>
    <div className="feature-grid privacy-grid">{tools.filter(t => ["proton","simplewall","ublock"].includes(t.id)).map(tool => <article className="feature-card" key={tool.id}><span className="feature-icon"><LockKeyhole/></span><div className="card-status"><span className={`status-dot ${tool.installed ? "good" : "unknown"}`}/>{tool.state}</div><h3>{tool.name}</h3><p>{tool.capability}. {tool.id === "simplewall" ? "simplewall uses WFP and is separate from Windows Defender Firewall." : "Only free capabilities are shown."}</p><button onClick={() => onOpen(tool.id)}>{tool.installed ? "Open official tool" : "View official setup"}<ExternalLink size={15}/></button></article>)}</div>
    <div className="notice"><Info/><span><strong>Choose one primary content blocker</strong><small>Use uBlock Origin on Firefox or uBlock Origin Lite on Chromium. Stacking content blockers can interfere with filtering. Privacy Badger remains an optional tracker-focused alternative.</small></span></div>
    <section className="layer-list"><h3>Privacy layers</h3><div><span>VPN</span><strong>Protects traffic in transit and changes the public IP seen by sites.</strong><em>Does not make accounts anonymous</em></div><div><span>Firewall</span><strong>Controls device network connections.</strong><em>Does not block web tracking by itself</em></div><div><span>Browser filtering</span><strong>Reduces ads and third-party tracking.</strong><em>Does not protect other applications</em></div><div><span>DNS</span><strong>Resolves site names for network connections.</strong><em>Review alongside VPN behavior</em></div></section></div>;
}

export function NetworkView({ gateway, adapter, onRouter }: { gateway: string; adapter: string; onRouter: () => void }) {
  const [guide, setGuide] = useState(false);
  return <div className="view-content"><SectionHeader title="Network settings" description="Review the active connection and open verified system or router controls."/>
    <div className="network-summary"><div className="network-hero"><span><Wifi/></span><div><small>Active network</small><h3>{adapter}</h3><p>Private profile · IPv4 and IPv6 enabled</p></div><span className="badge good-badge">Connected</span></div><dl className="detail-list wide"><div><dt>Default gateway</dt><dd>{gateway}</dd></div><div><dt>Router controls</dt><dd>http://{gateway}</dd></div><div><dt>DNS</dt><dd>Managed by Windows / VPN</dd></div><div><dt>VPN route</dt><dd>Observed locally</dd></div></dl><div className="button-row"><button onClick={onRouter}><ExternalLink size={16}/>Open router controls</button><button onClick={() => setGuide(!guide)}><SlidersHorizontal size={16}/>Change Wi-Fi password guide</button></div></div>
    {guide && <section className="guide-panel"><h3>Before changing your Wi-Fi password</h3><ol><li>Confirm you know the router administrator credentials. Sentinel Local never requests or stores them.</li><li>Changing the password disconnects every wireless device.</li><li>Reconnect trusted devices individually with the new password.</li><li>Use WPA2-AES or WPA3 and a unique, long passphrase.</li></ol><button onClick={onRouter}>Continue to router interface</button></section>}
    <div className="notice warning"><AlertTriangle/><span><strong>Router support varies</strong><small>ISP-managed routers may restrict settings. Sentinel Local will not flash firmware or claim universal control.</small></span></div></div>;
}

const memberTypes: Array<[DeviceProfile["type"], string]> = [["desktop", "Desktop"], ["laptop", "Laptop"], ["tv", "TV"], ["streaming", "Streaming device"], ["cellphone", "Cellphone"], ["unknown", "Unknown"]];

export function MembersView({ devices, onSave }: { devices: DeviceProfile[]; onSave: (id: string, label: string, trust: string, type: DeviceProfile["type"]) => void }) {
  const [editing, setEditing] = useState<DeviceProfile>();
  const [name, setName] = useState("");
  const [deviceType, setDeviceType] = useState<DeviceProfile["type"]>("unknown");
  const edit = (device: DeviceProfile) => { setEditing(device); setName(device.name); setDeviceType(device.type); };
  return <div className="view-content"><SectionHeader title="Network members" description="Label observed devices locally. Vendor and device-type guesses may be wrong."/>
    <section className="table-panel"><table><thead><tr><th>Device</th><th>Type</th><th>Address</th><th>Observed vendor</th><th>Trust</th><th>Last seen</th><th>Action</th></tr></thead><tbody>{devices.filter(d => !["pc","router"].includes(d.type)).map(d => <tr key={d.id}><td><strong>{d.name}</strong></td><td>{memberTypes.find(([id]) => id === d.type)?.[1] ?? d.type}</td><td>{d.ip}<small>{d.mac}</small></td><td>{d.vendor ?? "Not identified"}</td><td><span className={`badge ${d.trust === "unknown" ? "review-badge" : "good-badge"}`}>{d.trust}</span></td><td>{d.lastSeen}</td><td><button onClick={() => edit(d)}>Edit device</button></td></tr>)}</tbody></table></section>
    {editing && <div className="dialog-backdrop" role="presentation"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="edit-title"><h3 id="edit-title">Edit device</h3><p>The name and type stay on this PC. They do not identify a person or change router access.</p><label>Device name<input maxLength={80} value={name} onChange={event => setName(event.target.value)}/></label><label>Device type<select value={deviceType} onChange={event => setDeviceType(event.target.value as DeviceProfile["type"])}>{memberTypes.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><div className="dialog-actions"><button onClick={() => setEditing(undefined)}>Cancel</button><button className="primary-button" disabled={!name.trim()} onClick={() => { onSave(editing.id, name.trim(), "trusted", deviceType); setEditing(undefined); }}>Save device</button></div></div></div>}</div>;
}

export function DiagnosticsView({ results, onRun }: { results: DiagnosticResult[]; onRun: () => void }) {
  return <div className="view-content"><div className="section-heading heading-with-action"><div><h2>Diagnostics & repair</h2><p>Evidence-based checks with safe, reversible next steps.</p></div><button className="primary-button" onClick={onRun}><RefreshCw size={17}/>Run diagnostics</button></div>
    <div className="diagnostic-list">{results.map(result => <article key={result.id}><span className={`diag-icon ${result.severity}`}>{result.severity === "good" ? <CheckCircle2/> : <AlertTriangle/>}</span><div><h3>{result.check}</h3><p>{result.evidence}</p><small>{result.recommendation}</small></div><span className={`badge ${result.severity === "good" ? "good-badge" : "review-badge"}`}>{result.severity === "good" ? "Good" : "Review"}</span></article>)}</div>
    <div className="notice"><Info/><span><strong>Repairs remain safe</strong><small>Network resets, firewall changes, file removal, and adapter changes are simulated because they require a separately reviewed privileged implementation.</small></span></div><button className="secondary-download"><Download size={17}/>Generate privacy-redacted support report</button></div>;
}

export function SettingsView({ darkMode, onDarkMode }: { darkMode: boolean; onDarkMode: (enabled: boolean) => void }) { return <div className="view-content"><SectionHeader title="Settings" description="Local preferences for privacy, accessibility, and data retention."/><div className="settings-list"><label><span><strong>Dark mode</strong><small>Use the darker Sentinel Local color theme.</small></span><input aria-label="Dark mode" type="checkbox" checked={darkMode} onChange={event => onDarkMode(event.target.checked)}/></label><label><span><strong>Local event history</strong><small>Retain metadata-only security events for 30 days.</small></span><input type="checkbox" defaultChecked/></label><label><span><strong>Diagnostic detail</strong><small>Keep full paths out of logs unless explicitly enabled.</small></span><input type="checkbox"/></label><label><span><strong>Reduced motion</strong><small>Also follows the Windows motion preference.</small></span><input type="checkbox"/></label><label><span><strong>Unknown device alerts</strong><small>Notify when a new LAN neighbor is observed.</small></span><input type="checkbox" defaultChecked/></label></div><div className="notice success"><LockKeyhole/><span><strong>No telemetry</strong><small>Sentinel Local does not include analytics, advertising, subscriptions, remote accounts, or background data uploads.</small></span></div></div>; }
